apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodify-ai-ml
  namespace: moodify-production
  labels:
    app.kubernetes.io/name: moodify-ai-ml
    app.kubernetes.io/part-of: moodify
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: moodify-ai-ml
  template:
    metadata:
      labels:
        app.kubernetes.io/name: moodify-ai-ml
        app.kubernetes.io/part-of: moodify
    spec:
      containers:
        - name: ai-ml
          image: moodify-ai-ml:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: moodify-secrets
                  key: SPOTIFY_CLIENT_ID
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: moodify-secrets
                  key: SPOTIFY_CLIENT_SECRET
          resources:
            requests:
              cpu: "1000m"
              memory: "2Gi"
            limits:
              cpu: "4000m"
              memory: "8Gi"
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 20
