apiVersion: v1
kind: Service
metadata:
  name: moodify-backend
  namespace: moodify-production
  labels:
    app.kubernetes.io/name: moodify-backend
    app.kubernetes.io/part-of: moodify
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: moodify-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
