apiVersion: v1
kind: ConfigMap
metadata:
  name: moodify-config
  namespace: moodify-production
  labels:
    app.kubernetes.io/name: moodify
    app.kubernetes.io/part-of: moodify

data:
  REACT_APP_BACKEND_URL: "https://api.moodify.example.com"
  AI_ML_URL: "http://moodify-ai-ml:5000"
  REDIS_URL: "redis://moodify-redis:6379/1"
