apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: moodify-backend-hpa
  namespace: moodify-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moodify-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: moodify-ai-ml-hpa
  namespace: moodify-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moodify-ai-ml
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: moodify-frontend-hpa
  namespace: moodify-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moodify-frontend
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
