apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: moodify-production
resources:
  - namespace.yaml
  - configmap.yaml
  - secret-template.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - ai-ml-deployment.yaml
  - ai-ml-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - mongo-statefulset.yaml
  - mongo-service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
