apiVersion: v1
kind: Service
metadata:
  name: moodify-mongo
  namespace: moodify-production
  labels:
    app.kubernetes.io/name: moodify-mongo
    app.kubernetes.io/part-of: moodify
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: moodify-mongo
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
