apiVersion: v1
kind: Secret
metadata:
  name: moodify-secrets
  namespace: moodify-production
  labels:
    app.kubernetes.io/name: moodify
    app.kubernetes.io/part-of: moodify

type: Opaque
stringData:
  SECRET_KEY: "CHANGE_ME"
  MONGO_DB_URI: "mongodb://moodify-mongo:27017"
  MONGO_DB_USERNAME: "moodify"
  MONGO_DB_PASSWORD: "CHANGE_ME"
  SPOTIFY_CLIENT_ID: "CHANGE_ME"
  SPOTIFY_CLIENT_SECRET: "CHANGE_ME"
